// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartGrao.Infrastructure.Persistence;

#nullable disable

namespace SmartGrao.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SmartGraoDbContext))]
    [Migration("20260907235943_SamplingPlanOutdatedFlag")]
    partial class SamplingPlanOutdatedFlag
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartGrao.Domain.Farms.Farm", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("city");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Point>("Headquarters")
                        .HasColumnType("geography(Point,4326)")
                        .HasColumnName("headquarters");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("state")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_farms");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_farms_name");

                    b.ToTable("farms", (string)null);
                });

            modelBuilder.Entity("SmartGrao.Domain.Fields.Field", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<decimal>("AreaHectares")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("area_hectares");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Crop")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("crop");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<Polygon>("Geometry")
                        .IsRequired()
                        .HasColumnType("geography(Polygon,4326)")
                        .HasColumnName("boundary");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<double>("PerimeterMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("perimeter_meters");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_fields");

                    b.HasIndex("Geometry")
                        .HasDatabaseName("ix_fields_boundary_gist");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "gist");

                    b.HasIndex("FarmId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_fields_name_per_farm");

                    b.ToTable("fields", (string)null);
                });

            modelBuilder.Entity("SmartGrao.Domain.Sampling.SamplingPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double>("EdgeBufferMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("edge_buffer_meters");

                    b.Property<decimal>("FieldAreaHectares")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("field_area_hectares");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("field_id");

                    b.Property<bool>("IsOutdated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_outdated");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("mode");

                    b.Property<double>("SpacingMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("spacing_meters");

                    b.Property<bool>("SubdivisionRecommended")
                        .HasColumnType("boolean")
                        .HasColumnName("subdivision_recommended");

                    b.Property<int?>("TargetPointCount")
                        .HasColumnType("integer")
                        .HasColumnName("target_point_count");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sampling_plans");

                    b.HasIndex("FieldId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_sampling_plans_field_recent_first");

                    b.ToTable("sampling_plans", (string)null);
                });

            modelBuilder.Entity("SmartGrao.Domain.Sampling.SamplingPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography(Point,4326)")
                        .HasColumnName("location");

                    b.Property<Guid>("SamplingPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("sampling_plan_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.HasKey("Id")
                        .HasName("pk_sampling_points");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_sampling_points_location_gist");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("SamplingPlanId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_sampling_points_sequence_per_plan");

                    b.ToTable("sampling_points", (string)null);
                });

            modelBuilder.Entity("SmartGrao.Domain.Fields.Field", b =>
                {
                    b.HasOne("SmartGrao.Domain.Farms.Farm", null)
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fields_farms_farm_id");
                });

            modelBuilder.Entity("SmartGrao.Domain.Sampling.SamplingPlan", b =>
                {
                    b.HasOne("SmartGrao.Domain.Fields.Field", null)
                        .WithMany()
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sampling_plans_fields_field_id");
                });

            modelBuilder.Entity("SmartGrao.Domain.Sampling.SamplingPoint", b =>
                {
                    b.HasOne("SmartGrao.Domain.Sampling.SamplingPlan", null)
                        .WithMany("Points")
                        .HasForeignKey("SamplingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sampling_points_sampling_plans_sampling_plan_id");
                });

            modelBuilder.Entity("SmartGrao.Domain.Sampling.SamplingPlan", b =>
                {
                    b.Navigation("Points");
                });
#pragma warning restore 612, 618
        }
    }
}
